name: Build

env:
  TEST_DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5432/chatterworks_test?sslmode=disable"

on: push

jobs:

  build_and_deploy:
    name: Build
    runs-on: ubuntu-latest
    
    container:
      image:  node:10.16-jessie

    services:
      postgres:
        image: postgres
        # Password is required; provide default
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Port mapping required if running directly on runner machine
          - 5432:5432
      elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
          env:
            xpack.security.enabled: false
            discovery.type: single-node
          volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
          ports:
            - 9200:9200
            # - 9300:9300
          options: >-
            --health-cmd "curl http://localhost:9200/_cluster/health"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 10

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: cURL google.com
      run: |
        curl -X GET google.com

    - name: cURL elastic search
      run: |
        curl -X GET http://elasticsearch:9200/
